"""adding current_transfer_id column to TransactionModel table

Revision ID: b358f1eb9334
Revises: 7efa5ba1ebc1
Create Date: 2024-01-27 12:41:19.116889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b358f1eb9334'
down_revision = '7efa5ba1ebc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_transfer_id', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('current_transfer_id')

    # ### end Alembic commands ###
