"""add iban column to users table

Revision ID: d64f880ca4a3
Revises: 94c8215d0a65
Create Date: 2024-01-15 11:55:58.474485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64f880ca4a3'
down_revision = '94c8215d0a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban', sa.String(length=22), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('iban')

    # ### end Alembic commands ###
